[tls]
# cert_path = "./certs/example.com.pem"
# key_path  = "./certs/example.com.key"

[security]
# allow_origins = [
#     "https://example.com",
#     "https://*.cloudflareinsights.com",
# ]
allow_origins = ["*"]
csp_policy = """
default-src 'self'; \
script-src 'self' ; \
script-src-attr 'none'; \
style-src 'self' 'unsafe-inline'; \
img-src 'self' data:; \
connect-src 'self' ; \
font-src 'self'; \
object-src 'none'; \
base-uri 'self'; \
form-action 'self'; \
frame-ancestors 'none'\
"""
permissions_policy = "camera=(), microphone=(), geolocation=(), payment=()"
